# Generated by Django 5.1.1 on 2024-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("qualidadedoproduto", models.IntegerField()),
                ("tempoespera", models.IntegerField()),
                ("limpeza", models.IntegerField()),
                ("atendimento", models.IntegerField()),
                ("buffet", models.IntegerField()),
                ("cardapio", models.IntegerField()),
                ("ambiente", models.IntegerField()),
                ("preco", models.IntegerField()),
                ("nota", models.FloatField()),
                ("comentario", models.TextField()),
                ("anonimo", models.BooleanField(default=False)),
            ],
        ),
    ]
