# Generated by Django 5.1.1 on 2024-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Avalia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="data",
            field=models.DateField(auto_now_add=True),
        ),
    ]
